name = "ReSolverRegistry"
uuid = "1f67d619-c97e-4ec2-a5d7-4be415f23049"
repo = "git@github.com:The-ReSolver/ReSolverRegistry.git"
description = "Governing registry for the ReSolver packages (available at www.github.com/The-ReSolver)"

[packages]
0ac2d069-28cd-4d1e-aa57-4eb7242fcd6c = { name = "SPOD", path = "S/SPOD" }
28eb41cd-435a-4ede-8bdb-f2685fc03e8c = { name = "FDGrids", path = "F/FDGrids" }
333ac5fb-9ca8-4109-ae2c-88ac1dd5ecab = { name = "PoissonSolver", path = "P/PoissonSolver" }
54c0c897-3bff-4ba2-acae-d4c1acf2c14a = { name = "Fields", path = "F/Fields" }
5c307136-fb89-411d-b568-fbf16049e5ad = { name = "ChebUtils", path = "C/ChebUtils" }
6106e973-e982-47b2-ae8d-956f34fd3e5a = { name = "OptimWrapper", path = "O/OptimWrapper" }
701a43e8-2c5a-11e9-2d86-e5d483bb0ff0 = { name = "GMRES", path = "G/GMRES" }
8e664b2d-fea9-4945-a6a3-91764c96093d = { name = "ResolventAnalysis", path = "R/ResolventAnalysis" }
a8d363ce-860c-11ea-26b8-f7d5a45d10c5 = { name = "NKRoots", path = "N/NKRoots" }
abfb4c27-6a5b-4fca-8a0e-91ede93db49a = { name = "Projector", path = "P/Projector" }
e97b5281-e633-4c46-86d2-72ea63110c3f = { name = "DAESolve", path = "D/DAESolve" }
